version: "3.2"

services:
  db:
    build: .
    image: ghcr.io/tamugeoinnovation/mssqldocker
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_DB: ${MSSQL_DB}
      MSSQL_USER: ${MSSQL_USER}
      MSSQL_PASSWORD: ${MSSQL_PASSWORD}
    ports:
      - "1433:1433"
    container_name: mssql
